In [2]:
import numpy as np

In [7]:
# 3D (dimensional)
arr = np.array([[
    [1, 2, 3], [4, 5, 6], [1, 2, 4],
    [7, 8, 9], [10, 11, 12], [1, 1, 1]
]])

In [8]:
print(arr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 1  2  4]
  [ 7  8  9]
  [10 11 12]
  [ 1  1  1]]]


In [9]:
print(arr.shape) # Output of arr.shape is → (depth, rows, columns)

(1, 6, 3)


In [41]:
# 3D (dimensional)
arr1 = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[11, 21, 31], [42, 52, 62]]
])

In [13]:
print(arr1.shape) # Output of arr.shape is → (depth, rows, columns)

(2, 2, 3)


In [29]:
print(arr1[0, 1, 2])  # Access layer 0, row 1, column 2 → gets value 6

6


In [20]:
print(arr1[1, 1, 2])

6


In [21]:
print(arr1[1, 0, 2])

3


In [32]:
#Get row only
first_row = arr1[:, 0, :] #Get first row from both depth
print(first_row)

[[ 1  2  3]
 [11 21 31]]


In [44]:
#Get column only
first_column = arr1[:, :, 0] #Get first column only from all layer and all row.
print(first_column)

[[ 1  4]
 [11 42]]


In [45]:
arr1[:,:,1] = 0 #Selective column changes.
print(arr1)

[[[ 1  0  3]
  [ 4  0  6]]

 [[11  0 31]
  [42  0 62]]]
