In [6]:
import numpy as np
arr = np.array([1, 2, 3, 4, 6])
print(arr.dtype) #int64 or int32 depending on the system.

int32


In [15]:
arr1 = np.array([1.1, 2.232342, 3.32234, 4.4, 5.5])

In [16]:
print(arr1.dtype)

float64


In [17]:
arr1_int = arr1.astype(np.int64)

In [18]:
print(arr1_int)

[1 2 3 4 5]


In [20]:
print(arr1_int.dtype)

int64


In [21]:
#Downcasting to save memory
arr_large = np.array([1000, 2000, 3000, 4000], dtype = np.int64)

In [26]:
arr_small = arr_large.astype(np.int32)

In [33]:
print(arr_large)
print(arr_small)
print(arr_large.dtype)
print(arr_small.dtype)
#The output is same but the space they are occupying is different.

[1000 2000 3000 4000]
[1000 2000 3000 4000]
int64
int32


In [40]:
ar_int64 = np.array([1, 2, 3], dtype = np.int64)
ar_int32 = np.array([1, 2, 3], dtype = np.int32)
print(ar_int64.nbytes) # Output: 24 bytes (3 elements * 8 bytes each)
print(ar_int32.nbytes) # Output: 12 bytes (3 elements * 4 bytes each)

24
12


In [46]:
arr2 = np.array([1, 2, 'Palsang', "Waiba", "Python"])

In [66]:
print(arr2) #Unicode string array
print(arr2.dtype)

['1' '2' 'P' 'W' 'P']
<U1


In [64]:
arr2 = np.array([1, 2, 'Palsang', "Waiba", "Python"], dtype = 'U1')

In [67]:
print(arr2.dtype)

<U1


In [72]:
arr10 = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype='complex128')
print(arr10)
#Complex number data type

[1.+2.j 3.+4.j 5.+6.j]


In [71]:
arr = np.array([{'a': 1}, [1, 2, 3], 'hello'], dtype=object)
print(arr)
#Object data type

[{'a': 1} list([1, 2, 3]) 'hello']
