In [2]:
import numpy as np

In [17]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])

In [18]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [19]:
flat = arr.flatten()

In [20]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
flat[0]

1

In [22]:
flat[9]

10

In [23]:
flat[0:5] 

array([1, 2, 3, 4, 5])

In [24]:
flat[1:4]

array([2, 3, 4])

In [26]:
flat[::2] #Every second elemet

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [39]:
b = flat[3:7]

In [40]:
b

array([111,   5,   6,   7])

In [41]:
b[0] = 111 #Slicing returns a view not a copy.

In [45]:
b

array([111,   5,   6,   7])

In [44]:
flat

array([  1,   2,   3, 111,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15])

In [49]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])

In [51]:
arr1[[1,4,6]]

array([2, 5, 7])